name: pharma_bros_demo
description: A new Flutter project.
publish_to: 'none'

version: 0.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ">=7.8.0 <7.8.5"
  flutter:
    sdk: flutter
  dio: ^5.0.0
  go_router: ^13.1.0
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.3.3
  json_serializable:
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.10
  webview_flutter: ^4.5.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner:
  freezed:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/noto_sans_kr/NotoSansKR-Regular.ttf
